### ISSUE TITLE
Variables missing from CMIP6_SIday MIP table

### ISSUE THREAD

**Issue by ehogan** [PCMDI/xml-cmor3-database#14]
There are 8 variables in the SIday MIP table according to the [current version of the data request](http://clipc-services.ceda.ac.uk/dreq/u/MIPtable::SIday.html). However, there are only 2 variables in the [CMIP6_SIday.json MIP table](https://github.com/PCMDI/xml-cmor3-database/blob/master/src/CMIP6_SIday.json). I understand the current MIP tables have been generated from version 01.beta.45 of the data request, but it is my understanding that these variables have been in the SIday MIP table since at least version 01.beta.38 of the data request.

**Comment by dnadeau4** [comment]
@ehogan I think this has been fixed with the new release version.

**Comment by ehogan** [comment]
Looks good to me; thank you very much! :)
