### ISSUE TITLE
Not all MIP tables in the data request are being generated

### ISSUE THREAD

**Issue by ehogan** [PCMDI/xml-cmor3-database#2]
The list of MIP tables in [createAllTables.sh](https://github.com/PCMDI/xml-cmor3-database/blob/master/src/createAllTables.sh#L3) doesn't match the list of MIP tables in the [CMIP6 Data Request](http://clipc-services.ceda.ac.uk/dreq/index/miptable.html). Is there a way to auto-generate the list of MIP tables directly from the CMIP6 Data Request so that the correct MIP tables are generated?

**Comment by ehogan** [comment]
Also, the list of MIP tables in [copyAllTables.sh](https://github.com/PCMDI/xml-cmor3-database/blob/master/src/copyAllTables.sh#L3) should be the same as the list of MIP tables in [createAllTables.sh](https://github.com/PCMDI/xml-cmor3-database/blob/master/src/createAllTables.sh#L3) :)

**Comment by dnadeau4** [comment]
The list of MIP tables has not been set by the WIP yet.  I created the same one as CMIP5 and then realized that some of them are completely empty. 

For example

``` python
python CMORCreateTable.py -r cf3hr -j  
no Variable found for cf3hr
```

This is why there is inconsistencies between "copy" and "create" all tables.  After noticing the empty tables, I changed the "copy" script to make sure they are not in the repository.

Which ones are CMIP6?????
Here is the list of MIPs in my SQL database

``` python
>>> import CMOR3Table
>>> cursor=CMOR3Table.CMOR3Table()
>>> print " ".join([i[0] for i in cursor.getMipTables()])

"3hr 6hrLev 6hrPlev 6hrPlevpt Amon AmonAdj LIfxant LIfxgre LImon LImonant LImongre LIyrant LIyrgre Lmon Oclim Oday Ofx Omon Oyr SIday SImon aerdaily aerfixed aerhourly aermonthly cf3hr cfDay cfMon cfOff cfSites day em1hr em1hrclimmon em3hr em3hrpt emDay emDayZ emDaypt emFx emMon emMonZ emMonpt emSubhr emYr fx grids"
```

**Comment by ehogan** [comment]
The list of MIP tables in your SQL database matches with the MIP tables in the CMIP6 Data Request that I linked to in my first comment. Pull request #4 should resolve this issue :)

**Comment by dnadeau4** [comment]
I'll merge the pull request, but I know that all the MIP tables in the CMIP6 Data Request are not for CMIP6.

**Comment by dnadeau4** [comment]
All miptable files are created and pushed in 3 repositories.

**Comment by tfeb** [comment]
I guess the question is do we expect the mip tables in the DREQ to converge to be the CMIP6 ones?  I'd like to think the answer is 'yes' but I am actually sure it will be 'no'.

**Comment by dnadeau4** [comment]
@tfeb I like your the way you think! :smile:

**Comment by taylor13** [comment]
I think this issue can be closed (doing so now).  Anyone disagree?
