### ISSUE TITLE
MIP tables missing from 01.beta.27 update

### ISSUE THREAD

**Issue by ehogan** [PCMDI/xml-cmor3-database#3]
[CMIP6_cf3hr.json](https://github.com/PCMDI/xml-cmor3-database/blob/master/src/CMIP6_cf3hr.json) and [CMIP6_cfSites.json](https://github.com/PCMDI/xml-cmor3-database/blob/master/src/CMIP6_cfSites.json) are missing from the 01.beta.27 update (they have the commit messages `01.beta.36` and `update CMIP6 tables 01.Beta.26`, respectively).

**Comment by dnadeau4** [comment]
All fixed.
