### ISSUE TITLE
Cleaning up xml-cmor3-database

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/xml-cmor3-database#52]
This repo is cluttered with files that should either be removed or relocated.  Some of these files contain data that are still used by the code for creating CMIP6 tables but should be stored in a more compact and convenient format.

Here are some issues I have found with the repo:
 - [x] The CMIP6 table files for CMOR are in the source directory rather than the table directory of the repo.
 - [x] Although the application uses the XML provided from the DREQ, it also uses entries from the older CMIP5 tables.
 - [x] The CMIP5 tables contain a lot of unused data.
 - [x] The CMIP5 tables are in the libconfig format, which requires installing pylibconfig2 and pyparsing for parsing in Python.
 - [x] There are outdated and/or unused files in the repo.
 - [x] The process of creating CMIP6 CMOR tables requires running multiple scripts when it could be consolidated into one script.

I propose cleaning up this repo to help with updating the code, and to streamline the processing of the DREQ for creating new CMIP6 CMOR tables.

**Comment by durack1** [comment]
@mauzey1 thanks for pushing on this, I agree a thorough cleanup would be great. What you propose will aid maintenance going forward and also reduce confusion for parties interested in reusing parts of this code

@taylor13 ping

**Comment by taylor13** [comment]
I also support this.  Thanks!
I can probably help understanding what is needed from the tables, but maybe that is already obvious.  If any of it is redundant with what is available from the data request, we should probably switch to obtaining it from the data request.

**Comment by mauzey1** [comment]
@taylor13 @durack1 The convertXML.py script was only getting the following from the old table files.
- formula entries
- axis entries
- grid axes and variables

It's also gathering values from [Amon_libconfig](https://github.com/PCMDI/xml-cmor3-database/blob/master/src/Amon_libconfig) called [expt_ids](https://github.com/PCMDI/xml-cmor3-database/blob/master/src/expt_ids_libconfig) but that doesn't seem to be used for anything.  The rest of the variables are coming from the data request.

The code isn't even using all of the table files.
https://github.com/PCMDI/xml-cmor3-database/blob/ea84db85d88c06af3ed2a686ed0065c2234108bc/src/convertXML.py#L971
https://github.com/PCMDI/xml-cmor3-database/blob/ea84db85d88c06af3ed2a686ed0065c2234108bc/src/convertXML.py#L1116-L1118
https://github.com/PCMDI/xml-cmor3-database/blob/ea84db85d88c06af3ed2a686ed0065c2234108bc/src/convertXML.py#L1252

My plan is to get only the entries that convertXML.py is getting from the tables and put them into 3 JSON files for formulas, axes, and grid variables.

**Comment by taylor13** [comment]
Putting formulas and grid variables in separate json files seems like a good idea.  Not sure about "axes".  I think the "axes" *might* be obtainable from the data request.  The expt_id config file seems like it would be used for CMIP5, but not needed for CMIP6.

Besides the files you've mentioned, I assume that CMOR/PrePARE also get information directly from the CV's (like experiment_id).  Is that correct?

**Comment by mauzey1** [comment]
@taylor13 CMOR and PrePARE use information from the CV via CMIP6_CV.json, which is created by [a script in CMOR](https://github.com/PCMDI/cmor/blob/b1dee375bb2812afcecb88b33a1b6356034c996a/scripts/createCMIP6CV.py) using files from https://github.com//WCRP-CMIP/CMIP6_CVs.

**Comment by mauzey1** [comment]
All tasks for this issue have been completed.
