### ISSUE TITLE
Remove unused/old files

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/xml-cmor3-database#53]
There are files in this repo that are either outdated or not used in any part of the CMOR table creation process.  These include CMIP5 & CMIP6 tables that are not used, old versions of dreq.xml, and miscellaneous testing/sample files.

**Comment by durack1** [comment]
@mauzey1 thanks for this. I note the `CMIP6_DB.pptx` file is useful as a visual description of the dependencies of this repo, it would be good to keep this file, but in a structure that you suggest which is cleaner and easier to maintain

**Comment by mauzey1** [comment]
Yes, I plan to move that file into the doc folder.
